name: Docker Image CI
on: [push]
jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login 
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build e Push image
      run: |
        docker build --tag rafamtts/cicd-frontend:latest .
        docker tag rafamtts/cicd-frontend:latest rafamtts/cicd-frontend:$GITHUB_SHA
        docker push rafamtts/cicd-frontend
